-- ============================================================
-- SEED DE CATÁLOGO — GENERADO AUTOMÁTICAMENTE. NO EDITAR A MANO.
-- ============================================================
-- Fuente: src/data/storeMockData.ts y src/data/mockData.ts
-- Regenerar con: npm run db:seed:catalog
--
-- Todos los valores comerciales (precios, rendimientos, códigos) son
-- copia literal del dato de origen. No se inventó ningún dato.
-- ============================================================

-- MARCA
insert into public.brands (name, slug) values ('Pintuco', 'pintuco') on conflict (name) do nothing;

-- CATEGORÍAS (MÓDULO 4). Se crea un nodo raíz por taxonomía; las
-- categorías reales del negocio cuelgan de él como hijas.
insert into public.categories (kind, name, slug, sort_order) values
  ('PRODUCT', 'Catálogo Pintuco', 'catalogo-pintuco', 0),
  ('SOLUTION', 'Sistemas Pintuco', 'sistemas-pintuco', 0)
on conflict (kind, name) do nothing;

insert into public.categories (kind, parent_id, name, slug, sort_order) values ('PRODUCT', (select id from public.categories where kind='PRODUCT' and name='Catálogo Pintuco'), 'Fachadas & Exteriores', 'fachadas-exteriores', 1) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('PRODUCT', (select id from public.categories where kind='PRODUCT' and name='Catálogo Pintuco'), 'Vinilos & Interiores', 'vinilos-interiores', 2) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('PRODUCT', (select id from public.categories where kind='PRODUCT' and name='Catálogo Pintuco'), 'Impermeabilizantes', 'impermeabilizantes', 3) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('PRODUCT', (select id from public.categories where kind='PRODUCT' and name='Catálogo Pintuco'), 'Esmaltes & Metales', 'esmaltes-metales', 4) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('PRODUCT', (select id from public.categories where kind='PRODUCT' and name='Catálogo Pintuco'), 'Maderas & Barnices', 'maderas-barnices', 5) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('PRODUCT', (select id from public.categories where kind='PRODUCT' and name='Catálogo Pintuco'), 'Industriales & Epóxicos', 'industriales-epoxicos', 6) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('PRODUCT', (select id from public.categories where kind='PRODUCT' and name='Catálogo Pintuco'), 'Herramientas & Complementos', 'herramientas-complementos', 7) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Fachadas', 'fachadas', 1) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Interiores', 'interiores', 2) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Impermeabilización', 'impermeabilizacion', 3) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Metal', 'metal', 4) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Madera', 'madera', 5) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Industrial', 'industrial', 6) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Mantenimiento', 'mantenimiento', 7) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Fachadas & Exteriores', 'fachadas-exteriores', 8) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Vinilos & Interiores', 'vinilos-interiores', 9) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Impermeabilizantes', 'impermeabilizantes', 10) on conflict (kind, name) do nothing;
insert into public.categories (kind, parent_id, name, slug, sort_order) values ('SOLUTION', (select id from public.categories where kind='SOLUTION' and name='Sistemas Pintuco'), 'Esmaltes & Metales', 'esmaltes-metales', 11) on conflict (kind, name) do nothing;

-- SUPERFICIES (MÓDULO 6). is_frontend_type marca los literales que
-- existen en la unión SurfaceType de src/types/index.ts.
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Concreto', 'concreto', true, 0) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Cemento', 'cemento', true, 1) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Metal', 'metal', true, 2) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Madera', 'madera', true, 3) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Fachada', 'fachada', true, 4) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Drywall', 'drywall', true, 5) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Otra', 'otra', true, 6) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Revoque / Pañete', 'revoque-panete', false, 7) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Ladrillo a la vista', 'ladrillo-a-la-vista', false, 8) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Bloque', 'bloque', false, 9) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Mortero', 'mortero', false, 10) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Drywall / Yeso', 'drywall-yeso', false, 11) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Estuco', 'estuco', false, 12) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Concreto interior', 'concreto-interior', false, 13) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Madera aglomerada', 'madera-aglomerada', false, 14) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Teja de fibrocemento', 'teja-de-fibrocemento', false, 15) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Teja de barro', 'teja-de-barro', false, 16) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Mantos asfálticos previos', 'mantos-asfalticos-previos', false, 17) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Concreto fresco (>28 días)', 'concreto-fresco-28-dias', false, 18) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Mampostería', 'mamposteria', false, 19) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Ladrillo', 'ladrillo', false, 20) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Revoque', 'revoque', false, 21) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Juntas de dilatación', 'juntas-de-dilatacion', false, 22) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Hierro', 'hierro', false, 23) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Acero', 'acero', false, 24) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Rejas metálicas', 'rejas-metalicas', false, 25) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Portones', 'portones', false, 26) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Estructuras', 'estructuras', false, 27) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Puertas', 'puertas', false, 28) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Ventanas', 'ventanas', false, 29) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Pérgolas', 'pergolas', false, 30) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Decks', 'decks', false, 31) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Muebles de exterior', 'muebles-de-exterior', false, 32) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Pisos de concreto pulido', 'pisos-de-concreto-pulido', false, 33) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Morteros autonivelantes', 'morteros-autonivelantes', false, 34) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Pisos industriales', 'pisos-industriales', false, 35) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Muros lisos', 'muros-lisos', false, 36) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Muros semirrugosos', 'muros-semirrugosos', false, 37) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Fachadas', 'fachadas', false, 38) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Marcos', 'marcos', false, 39) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Zócalos', 'zocalos', false, 40) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Esquinas', 'esquinas', false, 41) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Biselados', 'biselados', false, 42) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Vidrio', 'vidrio', false, 43) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Aluminio', 'aluminio', false, 44) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Zócalos de madera', 'zocalos-de-madera', false, 45) on conflict (name) do nothing;
insert into public.surfaces (name, slug, is_frontend_type, sort_order) values ('Pinturas previas', 'pinturas-previas', false, 46) on conflict (name) do nothing;

-- PATOLOGÍAS (MÓDULO 7). Severidad por defecto MEDIA: la clasificación
-- técnica real la definirá el equipo de Pintuco, no se inventa aquí.
-- Las recomendaciones se poblarán en la FASE 6, al trasladar el motor
-- de diagnóstico que hoy vive en src/services/storage.ts.
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Buen estado', 'buen-estado', true, 0) on conflict (name) do nothing;
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Humedad', 'humedad', true, 1) on conflict (name) do nothing;
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Fisuras', 'fisuras', true, 2) on conflict (name) do nothing;
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Desprendimiento', 'desprendimiento', true, 3) on conflict (name) do nothing;
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Oxidación', 'oxidacion', true, 4) on conflict (name) do nothing;
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Desgaste', 'desgaste', true, 5) on conflict (name) do nothing;
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Hongos / Moho', 'hongos-moho', true, 6) on conflict (name) do nothing;
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Alcalinidad', 'alcalinidad', true, 7) on conflict (name) do nothing;
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Filtraciones', 'filtraciones', true, 8) on conflict (name) do nothing;
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Manchas', 'manchas', true, 9) on conflict (name) do nothing;
insert into public.pathologies (name, slug, is_frontend_type, sort_order) values ('Otro', 'otro', true, 10) on conflict (name) do nothing;

-- COLORES (28)
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-100', 'Blanco Puro', '#FFFFFF', '255, 255, 255', 'Blancos & Neutros', 'Viniltex Avanzada Mate', 'El blanco absoluto de Pintuco para máxima amplitud y luminosidad natural.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-101', 'Blanco Nieve', '#F8FAFC', '248, 250, 252', 'Blancos & Neutros', 'Koraza 5 Años Fachadas', 'Blanco sutilmente frío con alta reflexión de luz para fachadas modernas.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-102', 'Blanco Lino', '#F5F5F0', '245, 245, 240', 'Blancos & Neutros', 'Viniltex Avanzada Satinado', 'Tono marfil cálido y elegante para salas y habitaciones acogedoras.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-105', 'Gris Nevado', '#E2E8F0', '226, 232, 240', 'Blancos & Neutros', 'Koraza 5 Años Fachadas', 'Gris claro contemporáneo, ideal para contrastar con carpintería negra.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-304', 'Gris Urbano', '#64748B', '100, 116, 139', 'Blancos & Neutros', 'Koraza 5 Años / Viniltex', 'Gris medio sofisticado de carácter arquitectónico sobrio.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-308', 'Gris Antracita', '#334155', '51, 65, 85', 'Blancos & Neutros', 'Pintulux 3 en 1 / Koraza', 'Gris oscuro profundo para muros de acento, rejas y portones.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-204', 'Almendra Suave', '#EAE1D2', '234, 225, 210', 'Cálidos & Tierras', 'Viniltex Avanzada Mate', 'Calidez envolvente perfecta para comedores y zonas sociales.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-210', 'Arena Sahariana', '#EADBC8', '234, 219, 200', 'Cálidos & Tierras', 'Koraza 5 Años Fachadas', 'Tono desierto que disimula el polvo y armoniza con jardines.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-505', 'Terracota Colonial', '#C25E3B', '194, 94, 59', 'Cálidos & Tierras', 'Koraza 5 Años / Aquablock', 'Tierra rojiza tradicional de alta energía para exteriores y terrazas.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-220', 'Café Canela', '#8C5A3C', '140, 90, 60', 'Cálidos & Tierras', 'Madetec / Viniltex', 'Elegancia rústica para complementar maderas nobles.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-402', 'Azul Brisa Marina', '#BFDBFE', '191, 219, 254', 'Azules & Frescos', 'Viniltex Avanzada', 'Azul cielo pacífico que transmite serenidad y frescura térmica.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-410', 'Azul Caribe Profundo', '#2563EB', '37, 99, 235', 'Azules & Frescos', 'Viniltex / Pintulux', 'Azul vibrante que energiza estudios, locales y habitaciones juveniles.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-412', 'Azul Pintuco Corporativo', '#004F9F', '0, 79, 159', 'Azules & Frescos', 'Pintulux 3 en 1 Esmalte', 'El clásico e inconfundible azul institucional de confianza y solidez.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-418', 'Azul Noche Índigo', '#1E3A8A', '30, 58, 138', 'Azules & Frescos', 'Viniltex Avanzada Satinado', 'Azul oscuro de lujo para cabeceros de cama y paredes principales.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-318', 'Verde Salvia Natural', '#94A3B8', '148, 163, 184', 'Verdes & Naturales', 'Viniltex Avanzada Mate', 'Verde botánico apagado en tendencia biofílica para interiores zen.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-324', 'Verde Oliva Country', '#65A30D', '101, 163, 13', 'Verdes & Naturales', 'Koraza 5 Años Fachadas', 'Conexión directa con la naturaleza para casas campestres.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-330', 'Verde Bosque Andino', '#166534', '22, 101, 52', 'Verdes & Naturales', 'Pintulux 3 en 1 / Viniltex', 'Verde oscuro intenso para portones y paredes de biblioteca.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-T25-01', 'Dorado Amanecer 2025', '#FBBF24', '251, 191, 36', 'Tendencias 2025', 'Viniltex Avanzada Mate', 'Color del año Pintuco: optimismo radiante y calidez moderna.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-T25-02', 'Rosa Palo Silvestre', '#FDA4AF', '253, 164, 175', 'Tendencias 2025', 'Viniltex Avanzada Mate', 'Suavidad contemporánea que complementa metales dorados y negros.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-T25-03', 'Cobre Volcánico', '#EA580C', '234, 88, 12', 'Tendencias 2025', 'Koraza 5 Años Fachadas', 'Tono mineral con fuerza arquitectónica para muros focales.', true) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-IMP-01', 'Blanco Termo-Reflectivo', '#F8FAFC', null, 'Blancos & Neutros', null, null, false) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-IMP-02', 'Gris Techo', '#64748B', null, 'Blancos & Neutros', null, null, false) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-IMP-03', 'Rojo Colonial Teja', '#991B1B', null, 'Cálidos & Tierras', null, null, false) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-901', 'Negro Brillante', '#1E293B', null, 'Blancos & Neutros', null, null, false) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-900', 'Blanco Brillante', '#F8FAFC', null, 'Blancos & Neutros', null, null, false) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-905', 'Gris Plata', '#94A3B8', null, 'Blancos & Neutros', null, null, false) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-910', 'Azul Real', '#1D4ED8', null, 'Azules & Frescos', null, null, false) on conflict (code) do nothing;
insert into public.colors (code, name, hex, rgb, family, recommended_product, description, is_palette) values ('PNT-915', 'Verde Bosque', '#15803D', null, 'Verdes & Naturales', null, null, false) on conflict (code) do nothing;

-- PUNTOS DE RETIRO (7) — MÓDULO 19
insert into public.pickup_locations (external_ref, name, city, address, phone, hours, has_color_studio, has_tech_advisor, has_express_pickup, stock_readiness_hours) values ('store-med-poblado', 'Centro de Pinturas Pintuco - El Poblado', 'Medellín', 'Cra 43A # 18 Sur - 135 (Av. El Poblado)', '+57 (604) 444-2424', 'Lun - Vie: 7:30 AM - 6:00 PM | Sáb: 8:00 AM - 4:00 PM', true, true, true, 2) on conflict (external_ref) do nothing;
insert into public.pickup_locations (external_ref, name, city, address, phone, hours, has_color_studio, has_tech_advisor, has_express_pickup, stock_readiness_hours) values ('store-med-guayabal', 'Tienda Especializada Pintuco - Guayabal Constructores', 'Medellín', 'Calle 10 # 52 - 40 (Sector Guayabal)', '+57 (604) 385-9000', 'Lun - Vie: 7:00 AM - 5:30 PM | Sáb: 7:30 AM - 1:00 PM', true, true, true, 1) on conflict (external_ref) do nothing;
insert into public.pickup_locations (external_ref, name, city, address, phone, hours, has_color_studio, has_tech_advisor, has_express_pickup, stock_readiness_hours) values ('store-bog-norte', 'Pintuco Store - Bogotá Calle 134', 'Bogotá D.C.', 'Av. Cra 19 # 134 - 28', '+57 (601) 745-1200', 'Lun - Sáb: 8:00 AM - 6:30 PM | Dom: 9:00 AM - 2:00 PM', true, true, true, 2) on conflict (external_ref) do nothing;
insert into public.pickup_locations (external_ref, name, city, address, phone, hours, has_color_studio, has_tech_advisor, has_express_pickup, stock_readiness_hours) values ('store-bog-74', 'Centro de Soluciones Pintuco - Calle 74', 'Bogotá D.C.', 'Calle 74 # 22 - 18 (Sector 7 de Agosto)', '+57 (601) 310-8500', 'Lun - Vie: 7:30 AM - 6:00 PM | Sáb: 8:00 AM - 3:00 PM', true, true, true, 2) on conflict (external_ref) do nothing;
insert into public.pickup_locations (external_ref, name, city, address, phone, hours, has_color_studio, has_tech_advisor, has_express_pickup, stock_readiness_hours) values ('store-cali-pasoancho', 'Tienda Pintuco - Cali Pasoancho', 'Cali', 'Calle 13 (Pasoancho) # 66 - 45', '+57 (602) 330-4100', 'Lun - Sáb: 8:00 AM - 6:00 PM', true, true, true, 2) on conflict (external_ref) do nothing;
insert into public.pickup_locations (external_ref, name, city, address, phone, hours, has_color_studio, has_tech_advisor, has_express_pickup, stock_readiness_hours) values ('store-barranquilla-prado', 'Centro de Pinturas Pintuco - Barranquilla El Prado', 'Barranquilla', 'Cra 54 # 68 - 110', '+57 (605) 368-7000', 'Lun - Vie: 7:30 AM - 6:00 PM | Sáb: 8:00 AM - 2:00 PM', true, true, true, 2) on conflict (external_ref) do nothing;
insert into public.pickup_locations (external_ref, name, city, address, phone, hours, has_color_studio, has_tech_advisor, has_express_pickup, stock_readiness_hours) values ('store-bucaramanga-cabecera', 'Pintuco Store - Bucaramanga Cabecera', 'Bucaramanga', 'Cra 33 # 48 - 60', '+57 (607) 643-9000', 'Lun - Sáb: 8:00 AM - 6:00 PM', true, true, true, 2) on conflict (external_ref) do nothing;

-- PRODUCTOS (11) con sus variantes
insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-koraza-5', 'PNT-EXT-001', 'Koraza 5 Años Protección Total', 'Pintura elastomérica exterior antihongos con máxima resistencia a la intemperie y rayos UV', 'Pintura para exteriores 100% acrílica, base agua, diluible con agua. Máxima durabilidad con tecnología biosida activa contra hongos y algas. Puentea microfisuras de hasta 0.5 mm y repele agua de lluvia mientras permite transpirar al muro.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Fachadas & Exteriores'), 'Exterior', 'Mate', '20 a 25 m²/galón a 2 manos sobre superficie sellada', 22, 'Al tacto: 1 hora | Entre manos: 2 a 3 horas', array['Garantía de durabilidad de 5 años certificada', 'Puenteo elástico de microfisuras hasta 0.5 mm', 'Alta resistencia a la radiación UV y decoloración', 'Excelente lavabilidad y bajo ensuciamiento', 'Bajo olor y cero solventes agresivos (Bajo VOC)']::text[], 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=600', 'https://pintuco.com.co/fichas-tecnicas/koraza-5-anos.pdf', 4.9, 142, true, 'Más Vendido en Fachadas') on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-koraza-5'), 'pres-1', '1 Galón (3.785 L)', 'PNT-EXT-001-V1', 142900, 3.785, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-koraza-5'), 'pres-2', 'Cuñete 5 Galones (18.9 L)', 'PNT-EXT-001-V2', 629900, 18.9, 1) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-koraza-5'), 'pres-3', '1/4 Galón (0.946 L)', 'PNT-EXT-001-V3', 43900, 0.946, 2) on conflict (product_id, label) do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-koraza-5'), (select id from public.colors where code='PNT-101'), 0) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-koraza-5'), (select id from public.colors where code='PNT-105'), 1) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-koraza-5'), (select id from public.colors where code='PNT-210'), 2) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-koraza-5'), (select id from public.colors where code='PNT-505'), 3) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-koraza-5'), (select id from public.colors where code='PNT-304'), 4) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-koraza-5'), (select id from public.surfaces where name='Concreto')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-koraza-5'), (select id from public.surfaces where name='Revoque / Pañete')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-koraza-5'), (select id from public.surfaces where name='Ladrillo a la vista')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-koraza-5'), (select id from public.surfaces where name='Bloque')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-koraza-5'), (select id from public.surfaces where name='Mortero')) on conflict do nothing;

insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-viniltex-avanzada', 'PNT-INT-002', 'Viniltex Avanzada Máxima Lavabilidad', 'Pintura Tipo 1 superlavable con agentes antibacteriales y cero salpicadura', 'Vinilo Tipo 1 premium para interiores de altísimo desempeño. Fórmula con resina 100% acrílica modificada que permite remover manchas difíciles con facilidad. Con tecnología antimicrobiana que inhibe hasta el 99.9% de bacterias.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Vinilos & Interiores'), 'Interior', 'Mate', '40 a 50 m²/galón a 2 manos sobre superficie estucada', 45, 'Al tacto: 30 min | Segunda mano: 2 horas', array['Máxima lavabilidad (> 800 ciclos de lavado según NTC 1335)', 'Protección antibacterial y antihongos activa', 'Ultra cubrimiento desde la primera mano', 'Mínimo salpicado durante la aplicación con rodillo', 'Acabado uniforme sedoso y elegante']::text[], 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=600', 'https://pintuco.com.co/fichas-tecnicas/viniltex-avanzada.pdf', 4.8, 310, true, 'Nº 1 en Interiores') on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), 'pres-v1', '1 Galón (3.785 L)', 'PNT-INT-002-V1', 118900, 3.785, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), 'pres-v2', 'Cuñete 5 Galones (18.9 L)', 'PNT-INT-002-V2', 529000, 18.9, 1) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), 'pres-v3', '1/4 Galón (0.946 L)', 'PNT-INT-002-V3', 36900, 0.946, 2) on conflict (product_id, label) do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), (select id from public.colors where code='PNT-100'), 0) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), (select id from public.colors where code='PNT-102'), 1) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), (select id from public.colors where code='PNT-204'), 2) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), (select id from public.colors where code='PNT-402'), 3) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), (select id from public.colors where code='PNT-318'), 4) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), (select id from public.surfaces where name='Drywall / Yeso')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), (select id from public.surfaces where name='Estuco')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), (select id from public.surfaces where name='Cemento')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), (select id from public.surfaces where name='Concreto interior')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-viniltex-avanzada'), (select id from public.surfaces where name='Madera aglomerada')) on conflict do nothing;

insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-aquablock-techos', 'PNT-IMP-003', 'Aquablock Fibratado Techos & Terrazas 8 Años', 'Impermeabilizante elastomérico reforzado con fibras para losas, cubiertas y terrazas transitables', 'Impermeabilizante acrílico con fibras incorporadas que sustituyen la tela de refuerzo en áreas continuas. Altamente elástico, no se cuartea con el sol y resiste el tránsito peatonal liviano y estancamientos temporales de agua.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Impermeabilizantes'), 'Exterior', 'Satinado', '1.2 a 1.5 L/m² en 3 manos cruzadas (aprox. 12 m²/galón sistema completo)', 12, 'Entre manos: 3 a 4 horas | Curado total: 48 horas', array['Garantía de estanqueidad de 8 años', 'Fibras de polímero que evitan desgarros estructurales', 'Refleja hasta el 85% de radiación solar (aislamiento térmico)', 'Puentea fisuras de contracción en losas de concreto', 'Fácil aplicación en frío con rodillo o brocha']::text[], 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=600', 'https://pintuco.com.co/fichas-tecnicas/aquablock-techos.pdf', 4.9, 88, true, 'Máxima Impermeabilidad') on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-aquablock-techos'), 'pres-aq1', '1 Galón (3.785 L)', 'PNT-IMP-003-V1', 139900, 3.785, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-aquablock-techos'), 'pres-aq2', 'Cuñete 5 Galones (18.9 L)', 'PNT-IMP-003-V2', 599900, 18.9, 1) on conflict (product_id, label) do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-aquablock-techos'), (select id from public.colors where code='PNT-IMP-01'), 0) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-aquablock-techos'), (select id from public.colors where code='PNT-IMP-02'), 1) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-aquablock-techos'), (select id from public.colors where code='PNT-IMP-03'), 2) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-aquablock-techos'), (select id from public.surfaces where name='Concreto')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-aquablock-techos'), (select id from public.surfaces where name='Mortero')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-aquablock-techos'), (select id from public.surfaces where name='Teja de fibrocemento')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-aquablock-techos'), (select id from public.surfaces where name='Teja de barro')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-aquablock-techos'), (select id from public.surfaces where name='Mantos asfálticos previos')) on conflict do nothing;

insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-sellador-antialcalino', 'PNT-PREP-004', 'Sellador Antialcalino Pintuco Base Agua', 'Imprimante fijador que neutraliza la eflorescencia salina y uniformiza la absorción', 'Imprimación esencial para muros nuevos o intervenidos de concreto y revoque. Bloquea sales y humedad residual proveniente del sustrato, previniendo el ampollamiento y la decoloración de la pintura de acabado.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Fachadas & Exteriores'), 'Ambos', 'Mate', '25 a 35 m²/galón a 1 mano', 30, 'Al tacto: 45 min | Repinte: 2 horas', array['Bloquea el salitre y la alcalinidad del cemento fresco', 'Mejora la adherencia de pinturas de fachada hasta un 60%', 'Ahorra pintura de acabado al sellar la porosidad', 'Secado ultrarrápido al tacto en 45 minutos']::text[], 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600', 'https://pintuco.com.co/fichas-tecnicas/sellador-antialcalino.pdf', 4.8, 95, true, 'Paso 1 Obligatorio') on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-sellador-antialcalino'), 'pres-s1', '1 Galón (3.785 L)', 'PNT-PREP-004-V1', 89900, 3.785, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-sellador-antialcalino'), 'pres-s2', 'Cuñete 5 Galones (18.9 L)', 'PNT-PREP-004-V2', 389000, 18.9, 1) on conflict (product_id, label) do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-sellador-antialcalino'), (select id from public.surfaces where name='Concreto fresco (>28 días)')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-sellador-antialcalino'), (select id from public.surfaces where name='Revoque / Pañete')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-sellador-antialcalino'), (select id from public.surfaces where name='Mampostería')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-sellador-antialcalino'), (select id from public.surfaces where name='Ladrillo')) on conflict do nothing;

insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-masilla-elastomerica', 'PNT-PREP-005', 'Masilla Elastomérica Grietas & Fisuras Fachada', 'Masilla acrílica flexible para sello de fisuras y juntas con movimiento en exteriores', 'Compuesto elastomérico diseñado para sellar y reparar grietas de hasta 5 mm de ancho en muros exteriores e interiores. Gran elongación y memoria elástica, no se encoge ni se agrieta con la intemperie.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Fachadas & Exteriores'), 'Ambos', 'Texturizado', 'Rinde aprox. 15 metros lineales por cartucho de 300ml o 15 m² en fisurado general', 15, 'Al tacto: 2 horas | Lijado/Pintado: 12 horas', array['Elongación superior al 300% para absorber dilataciones térmicas', 'Pintable con cualquier vinilo o pintura elastomérica Pintuco', 'Excelente adherencia sobre concreto, mortero y mampostería', 'Uso interior y exterior bajo intemperie severa']::text[], 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=600', 'https://pintuco.com.co/fichas-tecnicas/masilla-elastomerica.pdf', 4.9, 74, true, 'Solución Antifisuras') on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-masilla-elastomerica'), 'pres-m1', 'Galón 4.5 Kg', 'PNT-PREP-005-V1', 68900, 3.785, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-masilla-elastomerica'), 'pres-m2', 'Cuñete 22 Kg', 'PNT-PREP-005-V2', 289000, 18.9, 1) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-masilla-elastomerica'), 'pres-m3', 'Cartucho 300 ml', 'PNT-PREP-005-V3', 22900, 0.3, 2) on conflict (product_id, label) do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-masilla-elastomerica'), (select id from public.surfaces where name='Concreto')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-masilla-elastomerica'), (select id from public.surfaces where name='Revoque')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-masilla-elastomerica'), (select id from public.surfaces where name='Juntas de dilatación')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-masilla-elastomerica'), (select id from public.surfaces where name='Mampostería')) on conflict do nothing;

insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-pintulux-3en1', 'PNT-MET-006', 'Pintulux 3 en 1 Anticorrosivo + Esmalte', 'Transforma el óxido, protege el metal y entrega acabado brillante duradero en 1 solo paso', 'Esmalte alquídico de alta tecnología que actúa directamente sobre superficies metálicas ferrosas, incluso con óxido adherido. Neutraliza la corrosión, sella e impermeabiliza, brindando un acabado brillante de alta resistencia.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Esmaltes & Metales'), 'Ambos', 'Brillante', '25 a 30 m²/galón a 2 manos', 28, 'Al tacto: 2 horas | Repinte: 6 a 8 horas', array['Elimina la necesidad de aplicar anticorrosivo previo', 'Se aplica directamente sobre óxido firme', 'Alto brillo y resistencia al rayado y tráfico', 'Resistente a la intemperie, lluvia y calor']::text[], 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=600', 'https://pintuco.com.co/fichas-tecnicas/pintulux-3en1.pdf', 4.7, 198, true, 'Directo al Óxido') on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-pintulux-3en1'), 'pres-p1', '1 Galón (3.785 L)', 'PNT-MET-006-V1', 124900, 3.785, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-pintulux-3en1'), 'pres-p2', '1/4 Galón (0.946 L)', 'PNT-MET-006-V2', 39900, 0.946, 1) on conflict (product_id, label) do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-pintulux-3en1'), (select id from public.colors where code='PNT-901'), 0) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-pintulux-3en1'), (select id from public.colors where code='PNT-900'), 1) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-pintulux-3en1'), (select id from public.colors where code='PNT-905'), 2) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-pintulux-3en1'), (select id from public.colors where code='PNT-910'), 3) on conflict do nothing;
insert into public.product_colors (product_id, color_id, sort_order) values ((select id from public.products where external_ref='prod-pintulux-3en1'), (select id from public.colors where code='PNT-915'), 4) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-pintulux-3en1'), (select id from public.surfaces where name='Hierro')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-pintulux-3en1'), (select id from public.surfaces where name='Acero')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-pintulux-3en1'), (select id from public.surfaces where name='Rejas metálicas')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-pintulux-3en1'), (select id from public.surfaces where name='Portones')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-pintulux-3en1'), (select id from public.surfaces where name='Estructuras')) on conflict do nothing;

insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-madetec-barniz', 'PNT-MAD-007', 'Madetec Barniz Poliuretano Exterior Filtro UV', 'Barniz transparente de máxima protección contra el sol, humedad y hongos en maderas', 'Barniz sintético formulado con resinas de poliuretano y filtros solares de última generación. Protege la madera contra la decoloración solar, lluvia y agentes biológicos, realzando las vetas naturales.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Maderas & Barnices'), 'Exterior', 'Brillante', '35 a 45 m²/galón a 1 mano', 40, 'Al tacto: 3 horas | Repinte: 12 horas', array['Filtro solar UV que previene el resecamiento y oscurecimiento', 'Película elástica que acompaña las dilataciones de la madera', 'Acabado cristalino brillante o semibrillante', 'Alta resistencia a hongos y termitas']::text[], 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?auto=format&fit=crop&q=80&w=600', 'https://pintuco.com.co/fichas-tecnicas/madetec-barniz.pdf', 4.8, 62, false, null) on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-madetec-barniz'), 'pres-md1', '1 Galón (3.785 L)', 'PNT-MAD-007-V1', 148900, 3.785, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-madetec-barniz'), 'pres-md2', '1/4 Galón (0.946 L)', 'PNT-MAD-007-V2', 46900, 0.946, 1) on conflict (product_id, label) do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-madetec-barniz'), (select id from public.surfaces where name='Puertas')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-madetec-barniz'), (select id from public.surfaces where name='Ventanas')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-madetec-barniz'), (select id from public.surfaces where name='Pérgolas')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-madetec-barniz'), (select id from public.surfaces where name='Decks')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-madetec-barniz'), (select id from public.surfaces where name='Muebles de exterior')) on conflict do nothing;

insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-epoxico-pintucoat', 'PNT-IND-008', 'Pintucoat Epóxico Alto Tráfico para Pisos', 'Recubrimiento epóxico de dos componentes para pisos de garajes, bodegas y clínicas', 'Sistema epóxico poliamida de alta resistencia química y mecánica. Soporta tráfico pesado de montacargas y vehículos, derrames de aceites, solventes y productos químicos de limpieza.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Industriales & Epóxicos'), 'Industrial', 'Brillante', '20 a 25 m²/galón a 2 manos (Kit Componente A + B)', 22, 'Tráfico liviano: 24 horas | Curado total: 7 días', array['Resistencia extrema al tráfico pesado y abrasión', 'Superficie continua higiénica y antipolvo', 'Resistente a aceites, gasolina y detergentes industriales', 'Cumple normas de asepsia para áreas alimenticias y de salud']::text[], 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=600', 'https://pintuco.com.co/fichas-tecnicas/pintucoat-pisos.pdf', 4.9, 45, false, 'Industrial Pesado') on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-epoxico-pintucoat'), 'pres-ep1', 'Kit 1 Galón (Comp A + B)', 'PNT-IND-008-V1', 249000, 3.785, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-epoxico-pintucoat'), 'pres-ep2', 'Kit Cuñete 5 Galones', 'PNT-IND-008-V2', 1089000, 18.9, 1) on conflict (product_id, label) do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-epoxico-pintucoat'), (select id from public.surfaces where name='Pisos de concreto pulido')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-epoxico-pintucoat'), (select id from public.surfaces where name='Morteros autonivelantes')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-epoxico-pintucoat'), (select id from public.surfaces where name='Pisos industriales')) on conflict do nothing;

insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-rodillo-antigota', 'PNT-HER-009', 'Rodillo Profesional Microfibra Antigota Pintuco 9"', 'Rodillo de alta retención para acabados parejos sin salpique en vinilos y fachadas', 'Herramienta profesional con felpa de microfibra termofusionada de 3/8" (9 mm). Proporciona una transferencia óptima de pintura sobre la pared sin salpicar ni dejar marcas de rodillazo.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Herramientas & Complementos'), 'Ambos', 'N/A', 'Ideal para proyectos de 20 a 500 m²', null, 'N/A', array['Microfibra de alta densidad sin desprendimiento de hilos', 'Mango ergonómico con rosca para extensión', 'Ahorra hasta un 25% de tiempo de aplicación', 'Fácil lavado y reutilizable más de 15 veces']::text[], 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=600', null, 4.9, 180, true, 'Herramienta Recomendada') on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-rodillo-antigota'), 'pres-rd1', 'Unidad Completa 9" (Felpa + Maneral)', 'PNT-HER-009-V1', 28900, null, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-rodillo-antigota'), 'pres-rd2', 'Repuesto Felpa 9"', 'PNT-HER-009-V2', 14900, null, 1) on conflict (product_id, label) do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-rodillo-antigota'), (select id from public.surfaces where name='Muros lisos')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-rodillo-antigota'), (select id from public.surfaces where name='Muros semirrugosos')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-rodillo-antigota'), (select id from public.surfaces where name='Drywall')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-rodillo-antigota'), (select id from public.surfaces where name='Fachadas')) on conflict do nothing;

insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-brocha-master', 'PNT-HER-010', 'Brocha Master Cerdas Mixtas Pintuco 3"', 'Brocha angular para recortes limpios en esquinas, marcos y detalles de fachada', 'Brocha con cerdas naturales y sintéticas de corte recto para un control milimétrico del trazo en remates y zócalos. Mango de madera balanceado y virola de acero inoxidable.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Herramientas & Complementos'), 'Ambos', 'N/A', 'N/A', null, 'N/A', array['Cerdas químicamente afiladas para un recorte perfecto', 'Excelente carga y descarga progresiva de pintura', 'No pierde cerdas durante la aplicación']::text[], 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600', null, 4.8, 112, false, null) on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-brocha-master'), 'pres-br1', 'Unidad 3 Pulgadas', 'PNT-HER-010-V1', 18900, null, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-brocha-master'), 'pres-br2', 'Unidad 2 Pulgadas', 'PNT-HER-010-V2', 14900, null, 1) on conflict (product_id, label) do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-brocha-master'), (select id from public.surfaces where name='Marcos')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-brocha-master'), (select id from public.surfaces where name='Zócalos')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-brocha-master'), (select id from public.surfaces where name='Esquinas')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-brocha-master'), (select id from public.surfaces where name='Biselados')) on conflict do nothing;

insert into public.products (external_ref, code, name, tagline, description, brand_id, category_id, environment, finish, coverage, spread_rate_m2_per_gal, drying_time, features, image_url, tech_sheet_url, rating, reviews_count, is_popular, badge) values ('prod-cinta-azul', 'PNT-HER-011', 'Cinta Azul Masking Profesional Pintuco 1.5"', 'Cinta de enmascarar de retiro limpio hasta 14 días sin dejar residuos de pegante', 'Cinta de papel crepé azul con adhesivo de polímero acrílico resistente a rayos UV. Brinda líneas de pintura nítidas y se retira fácilmente de molduras, marcos y vidrios sin dañar la superficie.', (select id from public.brands where name='Pintuco'), (select id from public.categories where kind='PRODUCT' and name='Herramientas & Complementos'), 'Ambos', 'N/A', 'Rollo de 50 metros', null, 'N/A', array['Líneas de pintura nítidas sin filtraciones', 'Remoción limpia hasta por 14 días bajo sol directo', 'Resistente a la humedad y pinturas base agua']::text[], 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=600', null, 4.9, 89, false, null) on conflict (external_ref) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-cinta-azul'), 'pres-ca1', 'Rollo 1.5" x 50m', 'PNT-HER-011-V1', 16900, null, 0) on conflict (product_id, label) do nothing;
insert into public.product_variants (product_id, external_ref, label, sku, price_cop, volume_liters, sort_order) values ((select id from public.products where external_ref='prod-cinta-azul'), 'pres-ca2', 'Pack 3 Rollos 1.5"', 'PNT-HER-011-V2', 44900, null, 1) on conflict (product_id, label) do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-cinta-azul'), (select id from public.surfaces where name='Vidrio')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-cinta-azul'), (select id from public.surfaces where name='Aluminio')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-cinta-azul'), (select id from public.surfaces where name='Zócalos de madera')) on conflict do nothing;
insert into public.product_surfaces (product_id, surface_id) values ((select id from public.products where external_ref='prod-cinta-azul'), (select id from public.surfaces where name='Pinturas previas')) on conflict do nothing;

-- INVENTARIO (MÓDULO 20)
-- Las cantidades se DERIVAN del `stockStatus` que ya traía cada
-- presentación en el mock, para no inventar existencias:
--   InStock -> 40 u.   LowStock -> 4 u.   PreOrder -> 0 u.
-- por cada punto de retiro.
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-1' and v.product_id=(select id from public.products where external_ref='prod-koraza-5') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-2' and v.product_id=(select id from public.products where external_ref='prod-koraza-5') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-3' and v.product_id=(select id from public.products where external_ref='prod-koraza-5') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-v1' and v.product_id=(select id from public.products where external_ref='prod-viniltex-avanzada') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-v2' and v.product_id=(select id from public.products where external_ref='prod-viniltex-avanzada') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-v3' and v.product_id=(select id from public.products where external_ref='prod-viniltex-avanzada') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-aq1' and v.product_id=(select id from public.products where external_ref='prod-aquablock-techos') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-aq2' and v.product_id=(select id from public.products where external_ref='prod-aquablock-techos') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-s1' and v.product_id=(select id from public.products where external_ref='prod-sellador-antialcalino') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-s2' and v.product_id=(select id from public.products where external_ref='prod-sellador-antialcalino') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-m1' and v.product_id=(select id from public.products where external_ref='prod-masilla-elastomerica') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-m2' and v.product_id=(select id from public.products where external_ref='prod-masilla-elastomerica') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-m3' and v.product_id=(select id from public.products where external_ref='prod-masilla-elastomerica') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-p1' and v.product_id=(select id from public.products where external_ref='prod-pintulux-3en1') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-p2' and v.product_id=(select id from public.products where external_ref='prod-pintulux-3en1') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-md1' and v.product_id=(select id from public.products where external_ref='prod-madetec-barniz') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-md2' and v.product_id=(select id from public.products where external_ref='prod-madetec-barniz') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-ep1' and v.product_id=(select id from public.products where external_ref='prod-epoxico-pintucoat') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 4 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-ep2' and v.product_id=(select id from public.products where external_ref='prod-epoxico-pintucoat') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-rd1' and v.product_id=(select id from public.products where external_ref='prod-rodillo-antigota') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-rd2' and v.product_id=(select id from public.products where external_ref='prod-rodillo-antigota') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-br1' and v.product_id=(select id from public.products where external_ref='prod-brocha-master') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-br2' and v.product_id=(select id from public.products where external_ref='prod-brocha-master') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-ca1' and v.product_id=(select id from public.products where external_ref='prod-cinta-azul') on conflict (variant_id, location_id) do nothing;
insert into public.inventory (variant_id, location_id, qty_available) select v.id, l.id, 40 from public.product_variants v cross join public.pickup_locations l where v.external_ref='pres-ca2' and v.product_id=(select id from public.products where external_ref='prod-cinta-azul') on conflict (variant_id, location_id) do nothing;

-- SOLUCIONES DEL CATÁLOGO (7) — is_kit = false
insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, badge, application, surface_summary, features, system_summary, durability_estimate, spread_rate_info, packagings, step_by_step_guide, color_swatches) values ('sol-01', 'Sistema Fachada Koraza Protección Extrema', (select id from public.categories where kind='SOLUTION' and name='Fachadas'), false, 'Sistema elastomérico bicapa de máxima durabilidad y repelencia al agua, diseñado para fachadas expuestas a intemperie severa, radiación UV y contaminación urbana.', 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&q=80&w=600', 'Más Solicitado', 'Fachadas de edificios, casas, muros perimetrales exteriores', 'Concreto, Mortero, Ladrillo limpio, Revoque', array['Puenteo de microfisuras de hasta 0.5 mm sin cuartearse', 'Hidrorrepelente con tecnología efecto loto autolimpiable con la lluvia', 'Protección antifúngica y antialgas por 5 a 7 años garantizados', 'Alta retención de color frente a luz solar directa y rayos UV']::text[], 'Sellador Antialcalino + Masilla Elastomérica + 2 Manos de Koraza', '5 a 7 años garantizados', '20-25 m²/galón a 2 manos (según rugosidad)', array['Galón (3.785 L)', 'Cuñete (5 Gal / 18.9 L)']::text[], array['Paso 1: Lavado a presión para retirar polvo, sales y material suelto.', 'Paso 2: Calafateo de fisuras con Masilla Elastomérica Pintuco.', 'Paso 3: Imprimación general con 1 mano de Sellador Antialcalino.', 'Paso 4: Aplicación de 2 manos cruzadas de Pintura Koraza 5 Años.']::text[], '[{"name":"Blanco Nieve","hex":"#F8FAFC"},{"name":"Arena Real","hex":"#FDE68A"},{"name":"Terracota","hex":"#EA580C"},{"name":"Gris Cemento","hex":"#94A3B8"},{"name":"Azul Pintuco","hex":"#004F9F"}]'::jsonb) on conflict (external_ref) do nothing;
insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, badge, application, surface_summary, features, system_summary, durability_estimate, spread_rate_info, packagings, step_by_step_guide, color_swatches) values ('sol-02', 'Sistema Viniltex Avanzado Cero Olor Antibacterial', (select id from public.categories where kind='SOLUTION' and name='Interiores'), false, 'Recubrimiento premium base agua de alta lavabilidad para ambientes interiores residenciales, comerciales e institucionales con requerimientos higiénicos.', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=600', 'Eco & Salud', 'Salas, habitaciones, oficinas, consultorios médicos, colegios', 'Drywall, Yeso, Estuco, Mampostería interior', array['Elimina el 99.9% de bacterias, hongos y virus en superficie', 'Ultra lavable con resistencia a más de 10,000 ciclos de frote', 'Bajo VOC y olor casi imperceptible para ocupación inmediata', 'Acabado mate sedoso uniforme de alta elegancia visual']::text[], 'Sellador Acrílico Interior + Estuco Profesional + 2 Manos Viniltex', 'Alta durabilidad lavable', '40-45 m²/galón a 2 manos', array['1/4 Galón', 'Galón', 'Cuñete (5 Gal)']::text[], array['Paso 1: Lijado suave y retiro de polvo residual.', 'Paso 2: Resane de imperfecciones con Estuco Acrílico.', 'Paso 3: Aplicación de 2 manos de Viniltex Avanzado con rodillo antigota.']::text[], '[{"name":"Blanco Puro","hex":"#FFFFFF"},{"name":"Marfil Suave","hex":"#FEF3C7"},{"name":"Gris Niebla","hex":"#E2E8F0"},{"name":"Celeste Zen","hex":"#E0F2FE"}]'::jsonb) on conflict (external_ref) do nothing;
insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, badge, application, surface_summary, features, system_summary, durability_estimate, spread_rate_info, packagings, step_by_step_guide, color_swatches) values ('sol-03', 'Sistema Pintuflex Impermeabilización Continua', (select id from public.categories where kind='SOLUTION' and name='Impermeabilización'), false, 'Membrana líquida elastomérica armada para cubiertas, terrazas, losas y techos con filtraciones o riesgo de estancamiento.', 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600', 'Protección Total', 'Cubiertas planas, techos inclinados, terrazas transitables ligeras', 'Concreto, Mortero cementicio, Manto asfáltico envejecido', array['Elongación superior al 300% para absorber dilataciones térmicas severas', 'Refuerzo con velo de fibra de poliéster para cero empalmes ni juntas', 'Resistencia directa a rayos solares UV y choque térmico', 'Fácil mantenimiento preventivo sin levantar sustrato']::text[], 'Imprimación Acrílica Diluida + Velo de Poliéster + 3 Manos Pintuflex', '5, 7 o 10 años según espesor', '1 m²/litro a 3 manos con tela (aprox. 18 m²/cuñete)', array['Galón', 'Cuñete (5 Gal)']::text[], array['Paso 1: Limpieza profunda y regularización de pendientes hacia sifones.', 'Paso 2: Imprimación diluida con agua 1:3 para anclaje.', 'Paso 3: Colocación de tela de refuerzo embebida en primera mano pura.', 'Paso 4: Aplicación de segunda y tercera mano cruzadas.']::text[], '[{"name":"Blanco Térmico (Reflectivo)","hex":"#F8FAFC"},{"name":"Rojo Teja","hex":"#B91C1C"},{"name":"Gris Cemento","hex":"#64748B"},{"name":"Verde Cubierta","hex":"#15803D"}]'::jsonb) on conflict (external_ref) do nothing;
insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, badge, application, surface_summary, features, system_summary, durability_estimate, spread_rate_info, packagings, step_by_step_guide, color_swatches) values ('sol-04', 'Sistema Pintulux Anticorrosivo & Esmalte Metálico', (select id from public.categories where kind='SOLUTION' and name='Metal'), false, 'Sistema integral de protección catódica y esmalte sintético poliuretánico para estructuras metálicas, barandas, rejas y tanques expuestos.', 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=600', null, 'Estructuras de acero, carpintería metálica, tuberías, techumbres', 'Acero al carbono, Hierro forjado, Metal galvanizado', array['Inhibidor activo contra la corrosión galvánica y salina', 'Excelente brillo, retención de color y dureza al impacto', 'Compatible con galvanizado previo acondicionador de superficie']::text[], 'Desengrasante + Anticorrosivo Cromato/Fosfato + Esmalte Pintulux', '3 a 5 años en ambientes urbanos', '25-30 m²/galón a 2 manos', array['1/4 Galón', 'Galón', 'Tambor (55 Gal)']::text[], array['Paso 1: Desoxidado manual o mecánico (lija grano 80 / cepillo de alambre).', 'Paso 2: Desengrase con solvente Pintuco.', 'Paso 3: 1 mano de Anticorrosivo Pintuco antes de 4 horas.', 'Paso 4: 2 manos de Esmalte Sintético Pintulux.']::text[], '[{"name":"Negro Brillante","hex":"#0F172A"},{"name":"Azul Pintuco","hex":"#004F9F"},{"name":"Gris Máquina","hex":"#475569"},{"name":"Verde Foresta","hex":"#166534"},{"name":"Aluminio Metal","hex":"#94A3B8"}]'::jsonb) on conflict (external_ref) do nothing;
insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, badge, application, surface_summary, features, system_summary, durability_estimate, spread_rate_info, packagings, step_by_step_guide, color_swatches) values ('sol-05', 'Sistema Maderin Preservante & Barniz Marino', (select id from public.categories where kind='SOLUTION' and name='Madera'), false, 'Tratamiento fungicida, insecticida e hidrófugo con acabado transparente o tonalizado para decks, pérgolas y carpintería de madera noble.', 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600', null, 'Pérgolas exteriores, puertas macizas, decks de piscina, muebles de madera', 'Maderas duras, Pino tratado, Teca, Cedro', array['Filtro solar UV que previene el agrisamiento de la veta', 'Protege contra termitas, carcoma y pudrición por humedad', 'Microporoso: permite que la madera respire sin descascararse']::text[], 'Lijado grano fino + Inmunizante Maderin + 3 Manos Barniz Marino', '2 a 4 años según exposición', '30-35 m²/galón a 1 mano', array['1/4 Galón', 'Galón']::text[], array['Paso 1: Lijado en sentido de la veta y retiro total de aserrín.', 'Paso 2: Impregnación fungicida con Inmunizante Maderin.', 'Paso 3: 3 manos de Barniz Marino con lijado intermedio ultra fino.']::text[], '[{"name":"Transparente Natural","hex":"#FEF3C7"},{"name":"Teca Cálida","hex":"#B45309"},{"name":"Caoba Intenso","hex":"#78350F"},{"name":"Nogal Clásico","hex":"#451A03"}]'::jsonb) on conflict (external_ref) do nothing;
insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, badge, application, surface_summary, features, system_summary, durability_estimate, spread_rate_info, packagings, step_by_step_guide, color_swatches) values ('sol-06', 'Sistema Pintuepox Tráfico Pesado & Pisos Industriales', (select id from public.categories where kind='SOLUTION' and name='Industrial'), false, 'Recubrimiento bicomponente epóxico y poliuretano alifático para plantas industriales, talleres, hangares y zonas de alto impacto químico/mecánico.', 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=600', 'Industrial Pesado', 'Pisos de fábricas, almacenes, zonas de carga, cocinas industriales', 'Concreto pulido, losas industriales, pisos con acabado CSP 3-4', array['Resistencia a derrames de aceites, solventes y ácidos diluidos', 'Soporta tráfico constante de montacargas de hasta 10 toneladas', 'Acabado antideslizante opcional con agregado de sílice calibrada', 'Fácil descontaminación y cumplimiento de normas sanitarias BPM']::text[], 'Perfilado Mecánico + Primer Epóxico 100% + Capa de Alto Espesor', '5 a 10 años con mantenimiento', '14-18 m²/galón según espesor en mils', array['Kit Galón (A+B)', 'Kit Cuñete (A+B)']::text[], array['Paso 1: Granallado o escarificado para perfil CSP-3.', 'Paso 2: Desengrase profundo y verificación de humedad < 4%.', 'Paso 3: Imprimación epóxica 100% sólidos.', 'Paso 4: Aplicación de capa auto-nivelante Pintuepox.']::text[], '[{"name":"Gris Tráfico","hex":"#64748B"},{"name":"Verde Seguridad","hex":"#15803D"},{"name":"Amarillo Señalización","hex":"#EAB308"},{"name":"Azul Industrial","hex":"#1E40AF"}]'::jsonb) on conflict (external_ref) do nothing;
insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, badge, application, surface_summary, features, system_summary, durability_estimate, spread_rate_info, packagings, step_by_step_guide, color_swatches) values ('sol-07', 'Sistema Solución Express Mantenimiento Institucional', (select id from public.categories where kind='SOLUTION' and name='Mantenimiento'), false, 'Kit de intervención rápida para reparaciones puntuales de humedad por capilaridad, salitre, desconche y retoques inmediatos en inmuebles operativos.', 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=80&w=600', null, 'Mantenimiento locativo en centros comerciales, colegios, bancos', 'Muros mixtos, zócalos, cielo rasos', array['Secado ultra rápido al tacto en menos de 30 minutos', 'Bloqueador de manchas de humo, grasa y humedad previa', 'Fácil aplicación sin necesidad de evacuar áreas adyacentes']::text[], 'Limpieza de eflorescencia + Bloqueador de Manchas + Acabado', 'Solución preventiva inmediata', '30 m²/galón', array['1/4 Galón', 'Galón']::text[], array['Paso 1: Cepillado de eflorescencias de salitre.', 'Paso 2: Bloqueador antihumedad Pintuco.', 'Paso 3: Acabado rápido.']::text[], '[{"name":"Blanco Universal","hex":"#FFFFFF"},{"name":"Gris Suave","hex":"#F1F5F9"}]'::jsonb) on conflict (external_ref) do nothing;

-- KITS COMPRABLES (4) — is_kit = true
insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, subtitle, problem_target, ideal_for, warranty, discount_percent, tools_included) values ('kit-fachada-5anos', 'Kit Fachada 5 Años Antifisuras & Humedad', (select id from public.categories where kind='SOLUTION' and name='Fachadas & Exteriores'), true, 'Fachada con microfisuras, humedad de lluvia y desgaste por intemperie', 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&q=80&w=800', 'El sistema completo especificado para fachadas residenciales y comerciales de 85 m²', 'Fachada con microfisuras, humedad de lluvia y desgaste por intemperie', 'Edificios residenciales, casas campestres y fachadas de locales en concreto', 'Garantía Pintuco 5 Años en Sistema Completo', 12, array['1 Rodillo Microfibra Antigota 9"', '1 Brocha Master Cerdas Mixtas 3"', '2 Rollos de Cinta Azul Masking Tape 1.5"', 'Guía técnica paso a paso de aplicación Pintuco']::text[]) on conflict (external_ref) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-fachada-5anos'), (select id from public.products where external_ref='prod-masilla-elastomerica'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-masilla-elastomerica' and v.label='1 Galón (4.5 Kg)'), '1 Galón (4.5 Kg)', 68900, 1, 'Preparación', 'Sellar y puentear grietas activas en revoque y concreto antes de pintar.', 1, 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=400', 1) on conflict (solution_id, step_number) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-fachada-5anos'), (select id from public.products where external_ref='prod-sellador-antialcalino'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-sellador-antialcalino' and v.label='Cuñete 5 Galones (18.9 L)'), 'Cuñete 5 Galones (18.9 L)', 389000, 2, 'Sellado', 'Fijar el sustrato, bloquear salitre alcalino y uniformizar absorción.', 1, 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=400', 2) on conflict (solution_id, step_number) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-fachada-5anos'), (select id from public.products where external_ref='prod-koraza-5'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-koraza-5' and v.label='Cuñete 5 Galones (18.9 L)'), 'Cuñete 5 Galones (18.9 L)', 629900, 3, 'Acabado', 'Capa elastomérica 100% impermeable con protección UV y antihongos.', 1, 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=400', 3) on conflict (solution_id, step_number) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-fachada-5anos'), (select id from public.products where external_ref='prod-rodillo-antigota'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-rodillo-antigota' and v.label='Pack Completo Obra'), 'Pack Completo Obra', 64700, 4, 'Herramienta', 'Herramientas recomendadas por Pintuco para un espesor de película parejo.', 1, 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=400', 4) on conflict (solution_id, step_number) do nothing;

insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, subtitle, problem_target, ideal_for, warranty, discount_percent, tools_included) values ('kit-antihumedad-interior', 'Kit Cero Humedad & Manchas Interiores', (select id from public.categories where kind='SOLUTION' and name='Vinilos & Interiores'), true, 'Muros interiores con humedad ascendente, manchas oscuras y hongos', 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=800', 'Tratamiento higiénico para muros con manchas de humedad, vapor y hongos de baño/cocina', 'Muros interiores con humedad ascendente, manchas oscuras y hongos', 'Apartamentos, baños, cocinas y habitaciones con ventilación limitada', 'Garantía Antibacterial Pintuco', 10, array['1 Rodillo Antigota 9"', '1 Brocha Master 2"', '1 Esponja abrasiva de limpieza previa']::text[]) on conflict (external_ref) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-antihumedad-interior'), (select id from public.products where external_ref='prod-sellador-antialcalino'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-sellador-antialcalino' and v.label='1 Galón'), '1 Galón', 54900, 1, 'Preparación', 'Elimina colonias de moho y bacterias hasta la raíz del poro.', 1, 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=400', 1) on conflict (solution_id, step_number) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-antihumedad-interior'), (select id from public.products where external_ref='prod-sellador-antialcalino'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-sellador-antialcalino' and v.label='1 Galón (3.785 L)'), '1 Galón (3.785 L)', 89900, 2, 'Sellado', 'Barrera química que impide la reaparición de eflorescencia salina.', 1, 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=400', 2) on conflict (solution_id, step_number) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-antihumedad-interior'), (select id from public.products where external_ref='prod-viniltex-avanzada'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-viniltex-avanzada' and v.label='Cuñete 5 Galones (18.9 L)'), 'Cuñete 5 Galones (18.9 L)', 529000, 3, 'Acabado', 'Pintura superlavable con escudo activo contra bacterias y hongos.', 1, 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=400', 3) on conflict (solution_id, step_number) do nothing;

insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, subtitle, problem_target, ideal_for, warranty, discount_percent, tools_included) values ('kit-techo-impermeable', 'Kit Techo & Terraza Impermeable 8 Años', (select id from public.categories where kind='SOLUTION' and name='Impermeabilizantes'), true, 'Goteras, filtraciones en losa de concreto y estancamientos de agua de lluvia', 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=800', 'Impermeabilización continua sin fisuras para losas transitables y cubiertas', 'Goteras, filtraciones en losa de concreto y estancamientos de agua de lluvia', 'Terrazas transitables, techos planos de concreto y losas de cubiertas', 'Garantía Estanqueidad 8 Años', 15, array['1 Cepillo de cerda dura para limpieza', '1 Rodillo de lana para impermeabilización', '1 Brocha de 4" para chaflanes y rincones']::text[]) on conflict (external_ref) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-techo-impermeable'), (select id from public.products where external_ref='prod-masilla-elastomerica'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-masilla-elastomerica' and v.label='Galón 4.5 Kg'), 'Galón 4.5 Kg', 68900, 1, 'Preparación', 'Tratar juntas de dilatación y grietas antes de la membrana.', 1, 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=400', 1) on conflict (solution_id, step_number) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-techo-impermeable'), (select id from public.products where external_ref='prod-aquablock-techos'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-aquablock-techos' and v.label='2 Cuñetes de 5 Galones'), '2 Cuñetes de 5 Galones', 599900, 2, 'Acabado', 'Membrana elástica continua reforzada con microfibras de poliéster.', 2, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=400', 2) on conflict (solution_id, step_number) do nothing;

insert into public.solutions (external_ref, name, category_id, is_kit, description, image_url, subtitle, problem_target, ideal_for, warranty, discount_percent, tools_included) values ('kit-metal-antioxidante', 'Kit Renovación Metal & Rejas Anticorrosivo', (select id from public.categories where kind='SOLUTION' and name='Esmaltes & Metales'), true, 'Metales oxidados, descascarados o expuestos a sol y lluvia', 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800', 'Tratamiento directo al óxido para portones, estructuras y cerramientos metálicos', 'Metales oxidados, descascarados o expuestos a sol y lluvia', 'Portones, rejas de fachada, barandas de balcones y vigas metálicas', 'Garantía Protección Anticorrosiva Pintuco', 10, array['1 Brocha angular 2.5" para rejas', '1 Lija grano 80 y 120 para desbaste', '1 Par de guantes de trabajo']::text[]) on conflict (external_ref) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-metal-antioxidante'), (select id from public.products where external_ref='prod-brocha-master'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-brocha-master' and v.label='Kit Acondicionamiento Metal'), 'Kit Acondicionamiento Metal', 29900, 1, 'Preparación', 'Retirar escamas sueltas de óxido y desengrasar el metal.', 1, 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=400', 1) on conflict (solution_id, step_number) do nothing;
insert into public.solution_products (solution_id, product_id, variant_id, presentation_label, unit_price_cop, step_number, phase, role_description, quantity_for_85m2, image_url, sort_order) values ((select id from public.solutions where external_ref='kit-metal-antioxidante'), (select id from public.products where external_ref='prod-pintulux-3en1'), (select v.id from public.product_variants v join public.products pr on pr.id=v.product_id where pr.external_ref='prod-pintulux-3en1' and v.label='1 Galón (3.785 L)'), '1 Galón (3.785 L)', 124900, 2, 'Acabado', 'Neutraliza el óxido y proporciona acabado brillante de alta protección.', 2, 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=400', 2) on conflict (solution_id, step_number) do nothing;

